---
abstract: 'A Moose based logging and reporting tool'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: '0.12'
  Filter::Util::Call: '1.55'
  Level1: '0'
  Modern::Perl: '0'
  Test2::Bundle::Extended: '0'
  Test2::Plugin::UTF8: '0'
  Test::File: '0'
  Test::Moose: '0'
configure_requires:
  Data::Walk::Extracted: '0.028'
  ExtUtils::MakeMaker: '7.04'
  Moose: '2.1804'
  MooseX::ShortCut::BuildInstance: '1.044'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.005, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Shiras
no_index:
  package:
    - Level1
    - Level2
    - Level3
    - MyCoolPackage
provides:
  Log::Shiras:
    file: lib/Log/Shiras.pm
    version: v0.37.3
  Log::Shiras::LogSpace:
    file: lib/Log/Shiras/LogSpace.pm
    version: v0.37.3
  Log::Shiras::Report:
    file: lib/Log/Shiras/Report.pm
    version: v0.37.3
  Log::Shiras::Report::CSVFile:
    file: lib/Log/Shiras/Report/CSVFile.pm
    version: v0.37.3
  Log::Shiras::Report::MetaMessage:
    file: lib/Log/Shiras/Report/MetaMessage.pm
    version: v0.37.3
  Log::Shiras::Report::Stdout:
    file: lib/Log/Shiras/Report/Stdout.pm
    version: v0.37.3
  Log::Shiras::Report::Test2Note:
    file: lib/Log/Shiras/Report/Test2Note.pm
    version: v0.37.3
  Log::Shiras::Switchboard:
    file: lib/Log/Shiras/Switchboard.pm
    version: v0.37.3
  Log::Shiras::TapPrint:
    file: lib/Log/Shiras/TapPrint.pm
    version: v0.37.3
  Log::Shiras::TapWarn:
    file: lib/Log/Shiras/TapWarn.pm
    version: v0.37.3
  Log::Shiras::Telephone:
    file: lib/Log/Shiras/Telephone.pm
    version: v0.37.3
  Log::Shiras::Test2:
    file: lib/Log/Shiras/Test2.pm
    version: v0.37.3
  Log::Shiras::Types:
    file: lib/Log/Shiras/Types.pm
    version: v0.37.3
  Log::Shiras::Unhide:
    file: lib/Log/Shiras/Unhide.pm
    version: v0.37.3
requires:
  Carp: '0'
  Clone: '0'
  Data::Dumper: '0'
  Data::Walk::Clone: v0.24.0
  Data::Walk::Extracted: v0.28.0
  Data::Walk::Graft: v0.28.0
  Data::Walk::Print: v0.28.0
  Data::Walk::Prune: v0.28.0
  DateTime: '0'
  Fcntl: '0'
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0'
  FileHandle: '0'
  IO::Callback: '0'
  IO::File: '0'
  JSON::XS: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Exporter: '0'
  Moose::Role: '0'
  MooseX::HasDefaults::RO: '0'
  MooseX::ShortCut::BuildInstance: v1.44.0
  MooseX::Singleton: '0'
  MooseX::StrictConstructor: '0'
  MooseX::Types: '0'
  MooseX::Types::Moose: '0'
  Test2::API: '0'
  Test2::Tools::Basic: '0'
  Text::CSV_XS: '0'
  constant: '0'
  if: '0'
  lib: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/jandrew/Log-Shiras/issues
  homepage: https://github.com/jandrew/Log-Shiras
  repository: https://github.com/jandrew/Log-Shiras.git
version: v0.37.3
x_authority: cpan:JANDREW
